### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by SteffanLong**

### CODE REVIEW

**Comment by Mulchman** [comment]
"Styled loss icons for colourblind people, because they are people too."

<3

**Comment by SteffanLong** [comment]
Let us know what you think! It's live now. We can always make changes. :)

**Comment by Mulchman** [comment]
The circle with the X for loss was a brilliant idea. I can see everything w/ these colorblind eyes. Thanks again for taking my reddit comment into consideration!

**Comment by SteffanLong** [comment]
@Mulchman We changed the icons in version 2.1. Please let us know what you think. We can always change them again.

**Pull request merged**
