### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by Marruk**
Hi guys!
I've sent you an email about this. I added a bit more styling/features compared to the screenshot, I think the only thing missing is the ability to change the fireteam members (not quite sure what the best place is for that) and an update for the Help overlay.

### CODE REVIEW

**Comment by SteffanLong** [comment]
This is absolutely beautiful.

**Comment by Marruk** [comment]
Cool, glad you like it :)

Small note:
In `/app/views/shared/header.html`at the bottom there is some ugly inline Javascript to initialize the Material Bootstrap theme, which is needed for the PSN/XBL toggle. My Angular knowledge is limited, so I couldn't find the correct place to put that initialisation. There is also quite some commented HTML in the views, which is all the old styling that I used to build the new screens.

**Comment by v-fedorov** [comment]
Since this is the first time either of us have received a pull request here, we are currently trying to figure out the best way for us to work together on this redesign before merging.

Some notes:
No need for a "Skilled player" box under the name, I dont want to assume someone is good or bad and there have been times where ive gotten my ass handed to me by really low KD players. Also its a lot of space we can use for other content.

I noticed you reduced the amount of "Last Matches", Currently we are showing last 25 games which I would like to keep. Maybe we can display two rows of 12 to compensate if all 25 on one row doesnt look as nice.

LOVE the weapon columns, I noticed you removed the weapon perk names which is good for design but without the names its hard to tell what im looking at at first glance. I think we can display two nodes per row like

(icon) name    (icon) name
(icon) name    (icon) name

We would have to truncate the names, ive had issues with this in the current design

The last match and stats tabs have to be added in, I am heavily attached to those lol

The new search bar is awesome, I really like it. But like you mentioned in the email we need to find another solution for searching the other characters (and recent players)

Maybe add another row under the main search bar with the two additional members search?

Im so conflicted on the intellect/discipline/strength, it looks so good but me and Steff have been way too obsessive about being able to cram as much as we can to save space.
What if they were horizontal rows?

Intellect    Discipline  Strength
--------       --------        --


Overall this design is amazing, hope you dont mind the tweaks.
I want this on live ASAP :)

**Comment by SteffanLong** [comment]
Personally I disagree with Vlad on the match history. We have the win percentage, so the match history honestly doesn't need to go back that far. The win streak indicator is just perfect for this also, as even if we only show 10 games, they could still be on a 25 game win streak (the max we would be able to show). And really, that's all we need to know.

As for the skill indicator, I think that's a fork in the direction we want to go with the website. I mean, it's just based on KD, so we are adding our interpretation of KD to the website. I like how our original design showed everything you could possibly want to know, and then let the user decide how to interpret it. It's also a lot of wasted space when KD is sufficient (in my opinion).

I also share Vlad's view on the Intellect Discipline Strength bars. They just waste too much space currently. I'd like to keep the website without scrollbars on a 'normal' resolution of 1080p.

**Comment by SteffanLong** [comment]
I prefer the way you did the weapon rows vs. the way we do it. I think the name of the weapon is more relevant at first glance than the weapon perk names, and those are still available by mousing over the icons. Also, any avid user of the website or player of Destiny would likely recognize the perk icons, so it's nice to use just the icons, and it saves some space.

**Comment by v-fedorov** [comment]
http://staging.destinytrialsreport.com

**Comment by SteffanLong** [comment]
For reference, we are working on SteffanLong/Marruk-master.

**Comment by Marruk** [comment]
Hi guys,

First of all, I'm from the Netherlands, so I have a bit of a differente time schedule :). Wall of text incoming!

##### Responses

My thought behind the "Skilled player" box is the idea that in one split second you can see whether you should look at the stats further. Three players "With other qualities"?: it doesn't really matter if they use shotgun or sniper. That's what I like about the "hazards" as well: DTR adds value to the data, making it more of a service.

On top of that I would love players on LFG to use terms like "You have to be an Above average player on Destiny Trials Report". That gives people a way to talk about DTR on other places, and puts DTR in an "authority"-role.

I agree that basing this only on KD is a bit weak, but I think we could improve on that a lot (with statusses like "Getting carried" (low KD, high win %).

In my ideal DTR world (an iteration on this concept) is that you can fill in your own fireteam, and based on the opponents DTR instantly gives you an indication whether it will be an "easy", "close" or "hard" match. Together with a summary of the opponents (two shotguns, one sniper, three sunsingers) DTR does all the work for you. But that might be something for later.

---------

I wasn't sure how much value 13 more matches added in that streak, so I decided to keep them on one line. One Trials run a week is usually no more than 7-12 matches, so a run of 25 would mean matches from over 2 weeks ago. I believe that together with "Streak" and "Win rate" that gives you enough information about the player.

---------

The idea behind the weapon icons is that the players that are interested in them are at a level of "hardcore-ism" that they recognise them. On top of that, more than half of those perks aren't really interesting to know, you are always looking for a select few (Final Round, the stupid accuracy thing for Shotgun). Plus, design wise it took away a lot of clutter on the screen.

---------

The reason I took out the "Last match" and "Stats" is because I don't think I have ever used them :). Do you maybe have Google Analytics stats on how much they are being used? I like the way the tabs look on staging now, so we can always add them.

As an alternative thought to tabs: we could embed "Last match" as a clickable toggle in the "Last matches" area, and the "Stats" as a clickable toggle in the Win rate / Streak / Rating area. It gives a nice layeredness to DTR: "Want to know more? Click on it and we service you!". It would also be an option to add the DestinyTracker link to there ("WANT TO KNOW EVEN MORE? Ok here you go").

---------

I've tried it with two additional search bars underneath, you can see that commented out in `header.html` I believe. I removed it because in my opinion it took to much space for the amount of times it's going to be used (I've found that around 4 in 5 times the fireteam based on recent players is correct). 

The alternative I had in mind is some kind of "Edit" or "Replace" button in the emblem area of the two fireteam members. By clicking that button the Gamertag (or whatever it's called on PS :)) could turn into an Input field, and "Level 34 bladedancer" into a smaller suggested players dropdown.

##### Other

A general thought on "cramming as much to save space": I think it's good practice to evaluate every pixel to see if it adds value to the user, but not at the cost of everything. As long as the most important information is available on first glance the user won't mind scrolling every one in a while, that type of data is only interesting in some cases.

---------

What I would love as a responsive solution to the fireteam members is that instead of scrolling up and down, you are able to swipe left / right. On a tablet you can already see two members, swiping shifts the focus to the middle and right one. A jQuery plugin that has all the functionalities we need is http://kenwheeler.github.io/slick/, but I haven't been able to implement it yet (I can't find the right place for the javascript initialisations with the dynamically loaded data).

---------

What's the reason that the player hazards are commented out, does it still need styling? I loved it as a functionality (again adding value to the data).

---------

Cheers!

**Comment by SteffanLong** [comment]
Merged with branch SteffanLong:Marruk-master

**Pull request closed without merging**
